version: '3.8'
services:
  php:
    build:
      target: development
    environment:
      SSL_MODE: "mixed"
#      PUID: '${UID:-1000}'
#      PGID: '${GID:-1000}'
      LARAVEL_SCHEDULER_ENABLED: '${LARAVEL_SCHEDULER_ENABLED:-true}'
      LARAVEL_QUEUE_ENABLED: '${LARAVEL_QUEUE_ENABLED:-true}'
    labels:
      - dev.orbstack.domains=*.advisingapp.local
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${APP_HTTPS_PORT:-443}:443'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - '.:/var/www/html'
    networks:
      - development
    depends_on:
      - redis
      - meilisearch
      - minio
      - mailpit
      - redshift
      - pgsql
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'advisingapp-redis:/data'
    networks:
      - development
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  meilisearch:
    image: 'getmeili/meilisearch:v1.2.0'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'advisingapp-meilisearch:/meili_data'
    networks:
      - development
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://localhost:7700/health'
      retries: 3
      timeout: 5s
  minio:
    image: 'minio/minio:RELEASE.2023-07-07T07-13-57Z'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
    environment:
      MINIO_ROOT_USER: advisingapp
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'advisingapp-minio:/data/minio'
    networks:
      - development
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - development
  pgsql:
    image: 'postgres:15'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'advisingapp-pgsql:/var/lib/postgresql/data'
      - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - development
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  redshift:
    image: 'postgres:15'
    ports:
      - '${FORWARD_SIS_DB_PORT:-5433}:5433'
    environment:
      PGPASSWORD: '${SIS_DB_PASSWORD:-secret}'
      POSTGRES_DB: '${SIS_DB_DATABASE}'
      POSTGRES_USER: '${SIS_DB_USERNAME}'
      POSTGRES_PASSWORD: '${SIS_DB_PASSWORD:-secret}'
    volumes:
      - 'advisingapp-redshift:/var/lib/postgresql/data'
      - './docker/pgsql/create-testing-sis-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    command: -p 5433
    networks:
      - development
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${SIS_DB_DATABASE}'
        - '-U'
        - '${SIS_DB_USERNAME}'
      retries: 3
      timeout: 5s
networks:
  development:
volumes:
  advisingapp-redis:
    driver: local
  advisingapp-meilisearch:
    driver: local
  advisingapp-minio:
    driver: local
  advisingapp-redshift:
    driver: local
  advisingapp-pgsql:
    driver: local
