name: Fix Code Style

on:
  push:

jobs:
  fix-code-style:
    runs-on: ubuntu-22.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        shell: bash

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install

      - name: Run Formatters
        run: composer format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: >
            chore: fix code style